package com.group3.backend.ui.model.request;

public class NewEmailRequest {
	private int alertId; //this will come from the alert. The alert will be generated by looking at medication counts

	public int getAlertId() {
		return alertId;
	}

	public void setAlertId(int alertId) {
		this.alertId = alertId;
	}

}
